import os

ADDON_DIR = os.path.dirname(os.path.abspath(__file__))
BLEND_FILE = "City_Generator2.0.blend"

# --- Dynamic Simulation Constants ---
DYNAMICS_COLLECTION_NAME = "Dynamic_Traffic"
DYNAMICS_ROAD_PATHS_COLLECTION = "Dynamic_Traffic_Paths"
DYNAMICS_SIDEWALK_PATHS_COLLECTION = "Dynamic_Sidewalk_Paths"
DYNAMICS_CARS_COLLECTION = "Dynamic_Cars"
DYNAMICS_PEDESTRIANS_COLLECTION = "Dynamic_Pedestrians"
DYNAMICS_TRAFFIC_LIGHTS_COLLECTION = "Dynamic_Traffic_Lights"

DEFAULT_CAR_DENSITY = 10
DEFAULT_CAR_SPEED_MIN = 5.0
DEFAULT_CAR_SPEED_MAX = 15.0
DEFAULT_PEDESTRIAN_DENSITY = 5
DEFAULT_PEDESTRIAN_SPEED = 1.5
DEFAULT_TRAFFIC_LIGHT_GREEN = 120
DEFAULT_TRAFFIC_LIGHT_YELLOW = 30
DEFAULT_TRAFFIC_LIGHT_RED = 120
DEFAULT_MIN_EDGE_LENGTH = 0.5
DEFAULT_SIDEWALK_OFFSET = 2.0
DEFAULT_CAR_FOLLOW_DISTANCE = 3.0
