import type {
  Asset,
  AuditLog,
  MultimodalCommand,
  PluginFunction,
  Project,
  RuntimeSetting,
  Scene,
  SceneTemplate,
  SimulationJob,
  SystemHealthItem,
  Task,
  User,
  VersionSnapshot,
} from '../../types/domain';

export const demoUsers: User[] = [
  {
    id: 'usr-modeler',
    name: '林知远',
    email: 'modeler@nku.city',
    role: 'modeler',
    department: '场景建模组',
    permissions: [
      'dashboard:view',
      'project:read',
      'project:write',
      'asset:replace',
      'layout:edit',
      'task:dispatch',
      'multimodal:execute',
      'audit:read',
    ],
  },
  {
    id: 'usr-analyst',
    name: '沈迭青',
    email: 'analyst@nku.city',
    role: 'analyst',
    department: '城市仿真分析组',
    permissions: [
      'dashboard:view',
      'project:read',
      'task:dispatch',
      'multimodal:execute',
      'simulation:run',
      'audit:read',
    ],
  },
  {
    id: 'usr-admin',
    name: '陈明策',
    email: 'admin@nku.city',
    role: 'admin',
    department: '平台治理与运维',
    permissions: [
      'dashboard:view',
      'project:read',
      'project:write',
      'asset:replace',
      'layout:edit',
      'task:dispatch',
      'multimodal:execute',
      'simulation:run',
      'audit:read',
      'version:rollback',
      'settings:write',
    ],
  },
];

export const initialProjects: Project[] = [
  {
    id: 'prj-riverside',
    name: '津湾河岸复合街区',
    owner: '林知远',
    status: 'active',
    cityScaleKm2: 1.2,
    coordinateSystem: 'CGCS2000 / Tianjin Local Grid',
    currentVersion: 'v18',
    updatedAt: '2026-05-24T15:20:00+08:00',
    sceneCount: 4,
    tags: ['滨水', '商业', '行人密集'],
  },
  {
    id: 'prj-airport',
    name: '空港新城交通韧性推演',
    owner: '沈迭青',
    status: 'review',
    cityScaleKm2: 3.6,
    coordinateSystem: 'WGS84 / UTM 50N',
    currentVersion: 'v09',
    updatedAt: '2026-05-23T20:08:00+08:00',
    sceneCount: 3,
    tags: ['交通', '应急', '枢纽'],
  },
  {
    id: 'prj-campus',
    name: '智慧校园人群疏散样板',
    owner: '陈明策',
    status: 'draft',
    cityScaleKm2: 0.8,
    coordinateSystem: 'CGCS2000 / Local Campus Grid',
    currentVersion: 'v04',
    updatedAt: '2026-05-22T10:42:00+08:00',
    sceneCount: 2,
    tags: ['校园', '人群', '安全'],
  },
];

export const initialScenes: Scene[] = [
  {
    id: 'scn-river-main',
    projectId: 'prj-riverside',
    name: '主河岸日间运营场景',
    status: 'editing',
    version: 'v18',
    templateId: 'tpl-waterfront',
    roadType: '慢行优先断面',
    treeType: '国槐 + 银杏混植',
    seatType: '滨水木质长椅',
    treeDensity: 72,
    roadWidth: 8,
    weather: '多云',
    timeOfDay: '16:30',
    objectCount: 4218,
    issueCount: 2,
  },
  {
    id: 'scn-river-night',
    projectId: 'prj-riverside',
    name: '夜景商业活动场景',
    status: 'ready',
    version: 'v15',
    templateId: 'tpl-commercial',
    roadType: '商业步行街断面',
    treeType: '法桐阵列',
    seatType: '模块化金属座椅',
    treeDensity: 58,
    roadWidth: 10,
    weather: '晴',
    timeOfDay: '20:00',
    objectCount: 3890,
    issueCount: 0,
  },
  {
    id: 'scn-airport-peak',
    projectId: 'prj-airport',
    name: '早高峰换乘压力场景',
    status: 'rendering',
    version: 'v09',
    templateId: 'tpl-transit',
    roadType: '公交优先断面',
    treeType: '低维护乔木',
    seatType: '候车廊一体座椅',
    treeDensity: 36,
    roadWidth: 14,
    weather: '阴',
    timeOfDay: '08:15',
    objectCount: 5631,
    issueCount: 4,
  },
  {
    id: 'scn-campus-evac',
    projectId: 'prj-campus',
    name: '体育馆散场疏散场景',
    status: 'ready',
    version: 'v04',
    templateId: 'tpl-campus',
    roadType: '校园混行道路',
    treeType: '白蜡 + 灌木带',
    seatType: '校园石材座椅',
    treeDensity: 66,
    roadWidth: 6,
    weather: '小雨',
    timeOfDay: '18:10',
    objectCount: 2045,
    issueCount: 1,
  },
];

export const initialAssets: Asset[] = [
  { id: 'asset-tree-ginkgo', name: '银杏树组 LOD2', type: '3d-model', format: 'glTF', status: 'available', license: 'CC-BY 4.0', sizeMb: 24 },
  { id: 'asset-road-asphalt', name: '透水沥青材质包', type: 'material', format: 'PBR', status: 'available', license: 'Internal', sizeMb: 88 },
  { id: 'asset-seat-wood', name: '滨水木质长椅', type: '3d-model', format: 'FBX', status: 'available', license: 'Internal', sizeMb: 17 },
  { id: 'asset-crowd-agent', name: '人群代理低模集合', type: 'crowd', format: 'glTF', status: 'available', license: 'Internal', sizeMb: 41 },
  { id: 'asset-boat-small', name: '小型电动船', type: 'vehicle', format: 'OBJ', status: 'deprecated', license: 'Restricted', sizeMb: 31, replacementFor: 'asset-boat-v2' },
  { id: 'asset-facade-glass', name: '玻璃幕墙纹理 2K', type: '2d-texture', format: 'PNG', status: 'missing', license: 'Unknown', sizeMb: 0, replacementFor: 'asset-facade-lowiron' },
];

export const initialTemplates: SceneTemplate[] = [
  {
    id: 'tpl-waterfront',
    name: '滨水活力街区',
    style: '亲水慢行 + 商业外摆',
    rulesVersion: 'tpl-r4.2',
    recommendedTree: '国槐 + 银杏混植',
    recommendedRoad: '慢行优先断面',
    recommendedSeat: '滨水木质长椅',
    densityRange: [50, 85],
    conflictHints: ['树木密度超过 82% 时需检查消防通道净宽。'],
  },
  {
    id: 'tpl-commercial',
    name: '商业步行街',
    style: '连续界面 + 夜间灯光',
    rulesVersion: 'tpl-r3.9',
    recommendedTree: '法桐阵列',
    recommendedRoad: '商业步行街断面',
    recommendedSeat: '模块化金属座椅',
    densityRange: [40, 70],
    conflictHints: ['外摆范围与消防登高面不能重叠。'],
  },
  {
    id: 'tpl-transit',
    name: '枢纽换乘片区',
    style: '公交优先 + 大客流组织',
    rulesVersion: 'tpl-r5.1',
    recommendedTree: '低维护乔木',
    recommendedRoad: '公交优先断面',
    recommendedSeat: '候车廊一体座椅',
    densityRange: [20, 55],
    conflictHints: ['公交港湾与人群排队区需保持 1.5m 缓冲。'],
  },
  {
    id: 'tpl-campus',
    name: '校园安全疏散',
    style: '低速混行 + 开放空间',
    rulesVersion: 'tpl-r2.7',
    recommendedTree: '白蜡 + 灌木带',
    recommendedRoad: '校园混行道路',
    recommendedSeat: '校园石材座椅',
    densityRange: [45, 75],
    conflictHints: ['应急疏散通道附近禁用固定座椅。'],
  },
];

export const initialFunctions: PluginFunction[] = [
  { name: 'replace_asset_batch', title: '批量资产替换', category: 'asset', description: '替换树木、座椅、建筑立面等目标对象。', enabled: true, risk: 'medium', schemaSummary: 'asset_id, target_type, scope', averageMs: 1180 },
  { name: 'apply_template_linkage', title: '模板联动配置', category: 'layout', description: '根据模板规则联动道路、树木、座椅与密度。', enabled: true, risk: 'low', schemaSummary: 'template_id, density, road_width', averageMs: 620 },
  { name: 'extract_sketch_topology', title: '草图点线提取', category: 'layout', description: '从草图或截图提取道路/边界拓扑。', enabled: true, risk: 'medium', schemaSummary: 'attachment_ref, scale, coordinate_system', averageMs: 1640 },
  { name: 'solve_point_layout', title: '点集布局求解', category: 'layout', description: '根据点集约束重建道路、地块和设施布局。', enabled: true, risk: 'medium', schemaSummary: 'point_set, topology_rules', averageMs: 1360 },
  { name: 'set_weather_lighting', title: '天气与天色控制', category: 'environment', description: '标准化天气、能见度、太阳高度与色温。', enabled: true, risk: 'low', schemaSummary: 'weather, time_of_day, visibility', averageMs: 410 },
  { name: 'dispatch_blender_job', title: 'Blender 插件下发', category: 'render', description: '将函数计划封装为插件任务并等待回执。', enabled: true, risk: 'high', schemaSummary: 'function_plan, idempotency_key', averageMs: 1920 },
  { name: 'run_traffic_simulation', title: '车辆仿真调度', category: 'simulation', description: '调度交通规则版本、OD 需求与随机种子。', enabled: true, risk: 'medium', schemaSummary: 'rules_version, od_profile, seed', averageMs: 2380 },
  { name: 'run_crowd_simulation', title: '人群仿真调度', category: 'simulation', description: '调度人群规则、避障半径、出口吸引力。', enabled: true, risk: 'medium', schemaSummary: 'rules_version, agent_count, seed', averageMs: 2450 },
  { name: 'rollback_scene_version', title: '版本回滚', category: 'governance', description: '恢复到指定场景快照并追加审计。', enabled: true, risk: 'high', schemaSummary: 'snapshot_id, reason', averageMs: 880 },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1001',
    traceId: 'trace-river-1001',
    projectId: 'prj-riverside',
    sceneId: 'scn-river-main',
    title: '主路两侧树木密度联动更新',
    functionName: 'apply_template_linkage',
    status: 'success',
    priority: 3,
    progress: 100,
    createdBy: '林知远',
    createdAt: '2026-05-24T15:11:00+08:00',
    elapsedMs: 914,
    dependsOn: [],
    retryable: false,
    params: { template_id: 'tpl-waterfront', tree_density: 72, road_width: 8 },
    resultObjects: ['road-main-01', 'tree-strip-07'],
    logs: ['schema 校验通过', '联动规则 tpl-r4.2 命中', 'Blender 回执 success'],
  },
  {
    id: 'task-1002',
    traceId: 'trace-river-1002',
    projectId: 'prj-riverside',
    sceneId: 'scn-river-main',
    title: '玻璃幕墙资产替换',
    functionName: 'replace_asset_batch',
    status: 'failed',
    priority: 4,
    progress: 61,
    createdBy: '林知远',
    createdAt: '2026-05-24T15:18:00+08:00',
    elapsedMs: 2500,
    dependsOn: ['task-1001'],
    retryable: true,
    params: { asset_id: 'asset-facade-glass', target_type: 'building_facade' },
    resultObjects: [],
    logs: ['schema 校验通过', '资产 asset-facade-glass 缺失', '已建议替代资产 asset-facade-lowiron'],
    errorCode: '2003',
  },
  {
    id: 'task-1003',
    traceId: 'trace-airport-1003',
    projectId: 'prj-airport',
    sceneId: 'scn-airport-peak',
    title: '早高峰车辆仿真调度',
    functionName: 'run_traffic_simulation',
    status: 'running',
    priority: 5,
    progress: 74,
    createdBy: '沈迭青',
    createdAt: '2026-05-24T14:42:00+08:00',
    elapsedMs: 3420,
    dependsOn: [],
    retryable: true,
    params: { rules_version: 'traffic-r3.2', seed: 20260506 },
    resultObjects: ['sim-airport-peak'],
    logs: ['OD profile 加载完成', 'SUMO adapter running', '轨迹缓存写入 74%'],
  },
];

export const initialCommands: MultimodalCommand[] = [
  {
    id: 'cmd-201',
    projectId: 'prj-riverside',
    sceneId: 'scn-river-main',
    modality: ['text', 'sketch'],
    rawInput: '把滨水步道两侧树木密度调高，湖面加入 3 条动态船只路径，天气改为傍晚小雨。',
    intentTag: 'green_space_weather_boat_update',
    confidence: 0.91,
    slots: { tree_density: 82, boat_paths: 3, weather: '小雨', time_of_day: '18:30' },
    plan: [
      { id: 'node-1', funcName: 'apply_template_linkage', title: '更新树木密度', status: 'approved', dependsOn: [], params: { tree_density: 82 } },
      { id: 'node-2', funcName: 'set_weather_lighting', title: '切换傍晚小雨', status: 'approved', dependsOn: [], params: { weather: '小雨', time_of_day: '18:30' } },
      { id: 'node-3', funcName: 'solve_point_layout', title: '生成船只路径', status: 'planned', dependsOn: ['node-1'], params: { boat_paths: 3 } },
    ],
    explanation: '指令被拆分为植被密度、环境光照和水域动态路径三个可审计函数。',
    createdAt: '2026-05-24T15:02:00+08:00',
    needsClarification: false,
  },
];

export const initialSimulations: SimulationJob[] = [
  {
    id: 'sim-river-traffic',
    projectId: 'prj-riverside',
    sceneId: 'scn-river-main',
    type: 'combined',
    status: 'completed',
    rulesVersion: 'traffic-r3.2 / crowd-r2.8',
    seed: 20260506,
    progress: 100,
    playbackTime: 38,
    durationMinutes: 60,
    startedAt: '2026-05-24T13:20:00+08:00',
    metrics: [
      { name: '平均车速', value: 28.4, unit: 'km/h', delta: 4.8, severity: 'good' },
      { name: '行人冲突点', value: 12, unit: '处', delta: -3, severity: 'normal' },
      { name: '路口延误', value: 46, unit: 's', delta: -12, severity: 'good' },
    ],
  },
  {
    id: 'sim-airport-peak',
    projectId: 'prj-airport',
    sceneId: 'scn-airport-peak',
    type: 'traffic',
    status: 'running',
    rulesVersion: 'traffic-r3.2',
    seed: 20260506,
    progress: 74,
    playbackTime: 31,
    durationMinutes: 90,
    startedAt: '2026-05-24T14:42:00+08:00',
    metrics: [
      { name: '拥堵指数', value: 0.71, unit: '', delta: 0.09, severity: 'bad' },
      { name: '公交准点率', value: 87, unit: '%', delta: -4, severity: 'normal' },
      { name: '排队溢出', value: 3, unit: '处', delta: 1, severity: 'bad' },
    ],
  },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'log-001', traceId: 'trace-river-1001', actor: '林知远', role: 'modeler', eventType: 'TASK_DISPATCH_SUCCESS', target: 'apply_template_linkage', severity: 'info', result: 'success', evidenceHash: 'sha256:9fd3a11c', createdAt: '2026-05-24T15:11:02+08:00' },
  { id: 'log-002', traceId: 'trace-river-1002', actor: '林知远', role: 'modeler', eventType: 'ASSET_VALIDATE_FAILED', target: 'asset-facade-glass', severity: 'warning', result: 'failed', evidenceHash: 'sha256:28ab4f9a', createdAt: '2026-05-24T15:18:11+08:00' },
  { id: 'log-003', traceId: 'trace-admin-401', actor: '陈明策', role: 'admin', eventType: 'PLUGIN_WHITELIST_UPDATE', target: 'rollback_scene_version', severity: 'critical', result: 'success', evidenceHash: 'sha256:72cd908e', createdAt: '2026-05-24T12:44:31+08:00' },
  { id: 'log-004', traceId: 'trace-airport-1003', actor: '沈迭青', role: 'analyst', eventType: 'SIMULATION_JOB_STARTED', target: 'sim-airport-peak', severity: 'info', result: 'pending', evidenceHash: 'sha256:ab901e21', createdAt: '2026-05-24T14:42:04+08:00' },
];

export const initialVersions: VersionSnapshot[] = [
  { id: 'ver-river-18', projectId: 'prj-riverside', sceneId: 'scn-river-main', version: 'v18', parentVersion: 'v17', author: '林知远', createdAt: '2026-05-24T15:21:00+08:00', summary: '滨水模板联动、树木密度调高、天气参数更新', changeCount: 38, rollbackable: true },
  { id: 'ver-river-17', projectId: 'prj-riverside', sceneId: 'scn-river-main', version: 'v17', parentVersion: 'v16', author: '林知远', createdAt: '2026-05-24T11:40:00+08:00', summary: '导入道路点集并重建街坊边界', changeCount: 62, rollbackable: true },
  { id: 'ver-airport-09', projectId: 'prj-airport', sceneId: 'scn-airport-peak', version: 'v09', parentVersion: 'v08', author: '沈迭青', createdAt: '2026-05-23T20:10:00+08:00', summary: '换乘区域公交优先断面与仿真规则更新', changeCount: 44, rollbackable: true },
  { id: 'ver-campus-04', projectId: 'prj-campus', sceneId: 'scn-campus-evac', version: 'v04', parentVersion: 'v03', author: '陈明策', createdAt: '2026-05-22T10:45:00+08:00', summary: '体育馆疏散路径与人群规则版本锁定', changeCount: 27, rollbackable: true },
];

export const initialSettings: RuntimeSetting[] = [
  { id: 'set-rbac-cache', title: 'RBAC 权限缓存', description: '登录后缓存角色菜单与按钮级权限，目标 P95 ≤ 1s。', value: true, category: 'rbac', locked: false },
  { id: 'set-llm-confidence', title: '低置信度澄清阈值', description: '低于阈值时禁止自动执行并触发澄清。', value: 0.72, category: 'llm', locked: false },
  { id: 'set-plugin-timeout', title: '轻量插件硬超时', description: 'Blender 插件任务超过该时长进入重试或人工接管。', value: 5, category: 'plugin', locked: false },
  { id: 'set-sim-refresh', title: '仿真刷新频率', description: '结果回放与可视化层刷新频率。', value: 10, category: 'simulation', locked: false },
  { id: 'set-audit-retention', title: '审计留存周期', description: '关键操作证据链保留月数。', value: 24, category: 'audit', locked: true },
];

export const initialHealth: SystemHealthItem[] = [
  { id: 'health-api', name: '控制平面 API', status: 'healthy', latencyMs: 42, successRate: 99.8, description: '认证、项目、任务编排入口' },
  { id: 'health-blender', name: 'Blender 插件执行器', status: 'degraded', latencyMs: 312, successRate: 97.6, description: '任务回执有轻微延迟' },
  { id: 'health-llm', name: 'LLM 多模态服务', status: 'healthy', latencyMs: 860, successRate: 98.9, description: '函数计划生成与澄清' },
  { id: 'health-sim', name: '仿真节点', status: 'healthy', latencyMs: 128, successRate: 99.2, description: '车辆与人群仿真队列' },
  { id: 'health-audit', name: '审计日志库', status: 'healthy', latencyMs: 23, successRate: 100, description: '追加写入与证据哈希' },
];
